### ISSUE TITLE
Add Material UI Resources ! 

### ISSUE THREAD

**Issue by rohitroy-github** [aaryan2134/Engineering-Resources#109]
I want to add Material UI resources under web development section as it is one of the most popular React component library. If it's relevant to the project, assign it to me, I'll have a check !

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.

**Comment by aaryan2134** [comment]
@prabhleenn It is being worked on by @rohitroy-github 
You can work on something else if you would like to

**Comment by rohitroy-github** [comment]
@aaryan2134, I have made a PR as a part of hacktoberfest by adding MUI resources to the list ! 
Please have a check and merge soon !

**Comment by rohitroy-github** [comment]
@aaryan2134, please merge the commit asap > It's one of my hacktoberfest contributions !

**Comment by prabhleenn** [comment]
@aaryan2134 please merge my PR.
