### ISSUE TITLE
Correct Links in Projects.MD

### ISSUE THREAD

**Issue by aaryan2134** [aaryan2134/Engineering-Resources#116]
![image](https://user-images.githubusercontent.com/22559451/198094780-0e1dbb42-b8ab-4e89-87c8-cd080538de08.png)
Correct the links according to the 1st link for the rest of them as well
Currently they are pointing to the forks of the respective contributor

**Comment by aaryan2134** [comment]
Let me know whoever is interested to work on this

**Comment by aaryan2134** [comment]
Sure

**Comment by jrenzzo** [comment]
Hello! I have worked on this and already submitted a PR :)
