### ISSUE TITLE
Adding resources

### ISSUE THREAD

**Issue by NeeravParakh** [aaryan2134/Engineering-Resources#18]
Adding "Data Structures and Algorithms - Self Paced", "Data Structures Easy to Advanced Course-FreeCodeCamp" in CS Resources and "100 Days of Machine Learning", "Machine Learning Course by Andrew NG" in Machine Learning Resources.

**Comment by aaryan2134** [comment]
Great! Seems good
You need to add 5 new resources for hacktoberfest
