### ISSUE TITLE
Addition of a TODO-List

### ISSUE THREAD

**Issue by kritsss** [aaryan2134/Engineering-Resources#35]
I want to add a TODO list which will be made by HTML, CSS and Javascript.

**Comment by its-kundan** [comment]
Assign me

**Comment by aaryan2134** [comment]
You can but you need to explain the various aspects learnt according to your curriculum. Only website will not be accepted. You can refer the contributing guidelines for details

**Comment by aaryan2134** [comment]
You can ask here if there is any issue
