### ISSUE TITLE
Correcting the indexing issues in the Readme

### ISSUE THREAD

**Issue by aaryan2134** [aaryan2134/Engineering-Resources#54]
If anyone is willing to correct the indexing issues then let me know in this thread.
There are a few sections that are not having their index currently and some are not working properly as well

**Comment by plopez26DPU** [comment]
Could you explain this more please

**Comment by siddarthpai** [comment]
hey! can i work on this issue, thanks!

**Comment by plopez26DPU** [comment]
!assign

**Comment by aaryan2134** [comment]
@plopez26DPU I have assigned you the issue. 
All the best

**Comment by plopez26DPU** [comment]
@Delvitron1019 , thanks, but I will work on it

**Comment by aaryan2134** [comment]
PR is submitted and is under review currently for this issue

**Comment by grow-xd** [comment]
Can i get assigned for this please

**Comment by grow-xd** [comment]
I will beautify the readme and make it more attractive

**Comment by plopez26DPU** [comment]
Please assign someone else.

**Comment by aaryan2134** [comment]
Let me know whoever is willing to work on this
https://github.com/aaryan2134/Engineering-Resources/pull/102
You can check this out and read the comments to know what needs to be done exactly

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.

**Comment by aaryan2134** [comment]
Sure @prabhleenn

**Comment by aaryan2134** [comment]
@prabhleenn Are you still working on this?

**Comment by slashgk** [comment]
@aaryan2134 I have raised a PR to remove the unnecessary tags. 
https://github.com/aaryan2134/Engineering-Resources/pull/148
