### ISSUE TITLE
Want to add resources of theory of automation.

### ISSUE THREAD

**Issue by noobtdbs** [aaryan2134/Engineering-Resources#59]
will be adding resources regarding to it

**Comment by aaryan2134** [comment]
Sure. You can add them directly in CS Resources and creating a sub topic inside that

**Comment by noobtdbs** [comment]
ok ..sure

**Comment by aaryan2134** [comment]
Please complete working on anyone issue before adding another one. I am closing your multiple issues. You can create a new one if you like to work on any particular part at one point of time
