### ISSUE TITLE
I want to add resources for learning 'R'

### ISSUE THREAD

**Issue by Delvitron1019** [aaryan2134/Engineering-Resources#66]

**Comment by aaryan2134** [comment]
Please don't add too many issues regarding adding resources. You can add any resources that are not already added yet.
Please follow the guidelines if there is any doubt

**Comment by Delvitron1019** [comment]
> Please don't add too many issues regarding adding resources. You can add any resources that are not already added yet. Please follow the guidelines if there is any doubt

So can you at least accept 1of these so I can add the resources?
