### ISSUE TITLE
Want to add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Sowham-3098** [aaryan2134/Engineering-Resources#8]
I want to add this and also want to add contributors profiles into main README.md file, if you want.
@aaryan2134 do you want this?

**Comment by aaryan2134** [comment]
I don't think this is necessary currently. 
If you want you can work on Code of Conduct

**Comment by Sowham-3098** [comment]
Ok then I will add the CODE of Conduct file

**Comment by aaryan2134** [comment]
If anyone else is willing to do this let me know here
