### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by Ritu-2001** [aaryan2134/Engineering-Resources#9]
I want to add a Mini project using of Dice Game using Html,CSS and Js.......
can please assign me ??

**Comment by aaryan2134** [comment]
Yes sure. You need to make sure you show how it is useful in any your core curriculum. 
Unfortunately we can't just add projects made for learning web dev/tutorial based projects. 
If you can add detailed description about your project showing its relevance in cs engineering courses then you go ahead with it

**Comment by Ritu-2001** [comment]
Okay ,,,,this project is made using html ,css and javascript,,,,,and here javascript function is used , i can elaborate function i think it is relevance for CS engineering ,,,,and I also add detailed description ,,,,where i add details description in anyother Folder or in README .file?

**Comment by aaryan2134** [comment]
Yeah. That's great. You can go ahead with it.
You can add it by creating a README.md file inside your project directory. You can have a look at contributing guidelines for specifics

**Comment by aaryan2134** [comment]
If you have encounter any issues you can share here
