### ISSUE TITLE
Updated Content Section for Web Development

### ISSUE THREAD

**Issue by aaryan2134** [aaryan2134/Engineering-Resources#99]
Please add all sub topics for web development in the index of the readme under Web Development
Also, link those to the sub sections as well

**Comment by aaryan2134** [comment]
Let me know here if you are interested to work on this

**Comment by spirtskhalava** [comment]
Can you explain better what needs to be done?

**Comment by aaryan2134** [comment]
Basically there are several sub topics in the web development section. So it would be better if these sub topics are accessible from the main index as well
Kind of like this

- Web Development
  - A
  - B
  - C

**Comment by Delvitron1019** [comment]
I am interested, assign it to me.

**Comment by aaryan2134** [comment]
Sure
